"""empty message

Revision ID: 4568a8c55ddc
Revises: 175ddbfe1ecc
Create Date: 2020-04-23 03:41:07.897473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4568a8c55ddc'
down_revision = '175ddbfe1ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_typeDESC')
    op.add_column('service_type', sa.Column('content', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_type', 'content')
    op.create_table('service_typeDESC',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('content', sa.VARCHAR(length=10000), nullable=True),
    sa.Column('service_type_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
