"""empty message

Revision ID: 8c8aea71e435
Revises: 75f0e3305745
Create Date: 2020-04-25 11:12:59.399128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8aea71e435'
down_revision = '75f0e3305745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_service', sa.Column('even', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_service', 'even')
    # ### end Alembic commands ###
