"""empty message

Revision ID: d141529dbcc0
Revises: 8c8aea71e435
Create Date: 2020-04-25 11:29:29.666843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd141529dbcc0'
down_revision = '8c8aea71e435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('even', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cloud_service')
    # ### end Alembic commands ###
